### ISSUE TITLE
use it in maya2020 

### ISSUE THREAD

**Issue by asdMild** [robertjoosten/maya-transfer-blend-shape#3]
i was try use it in maya2020, which is python2.7
and i try find the last support scipy 0.16.0 and numpy 1.11.0
i get this error 
transfer-blend-shape\scripts\transfer_blend_shape\transfer.py", line 280
and the scipy.linalg.norm function in 0.16 is no axis there, as it add when version at 0.17.0
ref: [https://docs.scipy.org/doc/scipy-0.16.1/reference/generated/scipy.linalg.norm.html](https://docs.scipy.org/doc/scipy-0.16.1/reference/generated/scipy.linalg.norm.html)
is there some way to get it in python2.7 in maya 2020,
or i can fix it by myself with a lit modify

**Comment by robertjoosten** [comment]
You would have to build a later version of numpy that works with Maya 2.7 python interpreter.
Googling numpy for maya 2020 yields some results.

https://forums.autodesk.com/t5/maya-programming/numpy-2018-2019/m-p/9394364#M11380
