### ISSUE TITLE
Error: file: C:/maya-transfer-blend-shape-master/transfer-blend-shape.mel line 280: No valid module information found matching

### ISSUE THREAD

**Issue by taoari** [robertjoosten/maya-transfer-blend-shape#4]
![image](https://user-images.githubusercontent.com/3815006/191374594-68cb2f94-bd72-4923-baad-82ff116246d0.png)

I am using Maya 2023, when I drag the .mel into Maya, I got the following error:

source "C:/maya-transfer-blend-shape-master/transfer-blend-shape.mel";
// Error: file: C:/maya-transfer-blend-shape-master/transfer-blend-shape.mel line 280: 
// No valid module information found matching the current version/language/platform of Maya in C:/maya-transfer-blend-shape-master/transfer-blend-shape.mod

There is no space in the path, what is the reason for this error? Thank you very much!

**Comment by robertjoosten** [comment]
That is now updated in the master branch.
Maya 2023 had to be added to the .mod file.
